@Obloo.Api.Server_HostAddress = https://localhost:7191

GET {{Obloo.Api.Server_HostAddress}}/weatherforecast/
Accept: application/json

###


POST {{Obloo.Api.Server_HostAddress}}/auth/register
Content-Type: application/json

{
  "firstName" : "Prabuddha",
  "lastName" : "Jayawardhana",
  "email": "admin1@gmail.com",
  "password" : "Admin@123"
}

###


POST {{Obloo.Api.Server_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password" : "Admin@123"
}

###
