version: '3.4'

services:
  # mongo:
  #   container_name: mongoserver
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodbvol:/data/db

  mssql:
    container_name: sqlserver
    restart: always
    ports:
      - "1433:1433"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"

  obloo.api.server:
    container_name: obloo.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_URLS=http://+:8080
      - JwtSettings__Secret=FB/5pJv9dQQLOKb1cq0TGrVaWFh2FrnoIWbA=
      - ConnectionStrings__TransactionConnectionString=Data Source=sqlserver,1433;Initial Catalog=Obloo;User ID=sa;Password=Admin@123;Trust Server Certificate=True
    depends_on:
      - mssql
    ports:
      - "8080:8080"